<?php
require_once 'config.php';
$auth = $_SESSION['auth'] ?? null;
if (!$auth) { header('Location: login.php'); exit; }

$company = [];
try { foreach ($pdo->query("SELECT setting_key,setting_value FROM company_settings") as $r) $company[$r['setting_key']]=$r['setting_value']; } catch(Exception $ignore){}
$company += ['company_name'=>'OKOYA FOOD COMPANY LIMITED','company_dept'=>'Staff Management & HR Department','company_address'=>'KM 7 Idi APA Community, Shaki, Oyo State, Nigeria','company_tagline'=>'POVERTY ERADICATION • REDUCE INEQUALITY • LEAVE NO ONE BEHIND'];

function e(?string $s):string{return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function fmtN($n):string{return '₦'.number_format((float)$n,2);}
function flash(string $type,string $msg):void{$_SESSION['flash']=['type'=>$type,'msg'=>$msg];}
function get_flash():?array{$f=$_SESSION['flash']??null;unset($_SESSION['flash']);return $f;}

if ($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='delete_order') {
    $id=(int)($_POST['order_id']??0);
    if($id>0){
        try{
            $pdo->prepare("DELETE FROM order_signatures WHERE order_id=?")->execute([$id]);
            $pdo->prepare("DELETE FROM payments WHERE order_id=?")->execute([$id]);
            $pdo->prepare("DELETE FROM order_status_history WHERE order_id=?")->execute([$id]);
            $pdo->prepare("DELETE FROM orders WHERE id=?")->execute([$id]);
            flash('success','Order deleted successfully.');
        }catch(Exception $e){flash('error','Delete failed: '.$e->getMessage());}
    }
    header('Location: order_register.php');exit;
}

if ($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='update_order_full') {
    $id=(int)($_POST['order_id']??0);
    if($id>0){
        try{
            $kg=floatval($_POST['kilograms']??0);$up=floatval($_POST['unit_price']??0);$tot=$kg*$up;
            $truckPrice=floatval($_POST['truck_price']??0);$newStatus=$_POST['status']??'Pending';$isPaid=isset($_POST['is_paid'])?1:0;
            $pdo->prepare("UPDATE orders SET order_type=?,order_date=?,description=?,kilograms=?,unit_price=?,total_amount=?,truck_price=?,departure_location=?,destination_location=?,status=?,is_paid=? WHERE id=?")
                ->execute([$_POST['order_type']??'outbound',$_POST['order_date']??date('Y-m-d'),trim($_POST['description']??''),$kg,$up,$tot,$truckPrice?:null,trim($_POST['departure_location']??'')?:null,trim($_POST['destination_location']??'')?:null,$newStatus,$isPaid,$id]);
            if($isPaid){$pdo->prepare("UPDATE payments SET status='Paid',paid_at=NOW() WHERE order_id=?")->execute([$id]);}
            else{$pdo->prepare("UPDATE payments SET status='Unpaid',paid_at=NULL WHERE order_id=?")->execute([$id]);}
            $bank=trim($_POST['bank']??'');$accNo=trim($_POST['account_no']??'');$accName=trim($_POST['account_name']??'');
            if($bank||$accNo||$accName){
                $clientId=null;try{$st=$pdo->prepare("SELECT client_id FROM orders WHERE id=?");$st->execute([$id]);$row=$st->fetch();if($row)$clientId=(int)$row['client_id'];}catch(Exception $ignore){}
                if($clientId){$pdo->prepare("UPDATE clients SET bank_name=COALESCE(NULLIF(?,''),bank_name),bank_account_no=COALESCE(NULLIF(?,''),bank_account_no),bank_account_name=COALESCE(NULLIF(?,''),bank_account_name) WHERE id=?")->execute([$bank,$accNo,$accName,$clientId]);}
            }
            try{$pdo->prepare("INSERT INTO order_status_history (order_id,new_status,changed_by,note) VALUES(?,?,?,?)")->execute([$id,$newStatus,$auth['id'],'Full edit via Order Register']);}catch(Exception $ignore){}
            flash('success','Order updated successfully.');
        }catch(Exception $e){flash('error','Update failed: '.$e->getMessage());}
    }
    header('Location: order_register.php');exit;
}

$search=trim($_GET['search']??'');$filterStatus=$_GET['status']??'';$filterDate=$_GET['date']??'';
$hasFilter=($search!==''||$filterStatus!==''||$filterDate!=='');
$where=[];$params=[];
if($search!==''){$where[]="(o.order_no LIKE ? OR c.name LIKE ? OR c.phone LIKE ? OR o.departure_location LIKE ? OR o.destination_location LIKE ?)";$params[]="%$search%";$params[]="%$search%";$params[]="%$search%";$params[]="%$search%";$params[]="%$search%";}
if($filterStatus!==''){$where[]="o.status=?";$params[]=$filterStatus;}
if($filterDate!==''){$where[]="o.order_date=?";$params[]=$filterDate;}
$whereClause=$where?'WHERE '.implode(' AND ',$where):'';
$limitClause=$hasFilter?'':'LIMIT 10';

try{
    $sql="SELECT o.id,o.order_no,o.order_type,o.order_date,o.description,o.kilograms,o.unit_price,o.total_amount,o.truck_price,o.departure_location,o.destination_location,o.status,o.is_paid,o.driver_id,o.created_at,c.name AS client_name,c.phone AS client_phone,c.email AS client_email,p.name AS product_name,p.code AS product_code,p.image_url AS product_img,pay.bank_name,pay.account_no,pay.account_name,d.full_name AS driver_name,d.vehicle_plate AS driver_plate FROM orders o JOIN clients c ON c.id=o.client_id JOIN products p ON p.id=o.product_id LEFT JOIN payments pay ON pay.order_id=o.id LEFT JOIN drivers d ON d.id=o.driver_id $whereClause ORDER BY o.created_at DESC $limitClause";
    $st=$pdo->prepare($sql);$st->execute($params);$orders=$st->fetchAll(PDO::FETCH_ASSOC);
}catch(Exception $e){$orders=[];}

try{
    $totalOrders=(int)$pdo->query("SELECT COUNT(*) FROM orders")->fetchColumn();
    $totalRevenue=(float)$pdo->query("SELECT IFNULL(SUM(amount),0) FROM payments WHERE status='Paid'")->fetchColumn();
    $pendingCount=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status='Pending'")->fetchColumn();
    $deliveredCnt=(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status='Delivered'")->fetchColumn();
}catch(Exception $e){$totalOrders=$totalRevenue=$pendingCount=$deliveredCnt=0;}

$flashData=get_flash();
?>
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
<title>Order Register | <?php echo e($company['company_name']); ?></title>
<link rel="icon" href="logo.ico">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/sora@5.0.0/index.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/manrope@5.0.0/index.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fontsource/jetbrains-mono@5.0.0/index.css">
<style>
*{margin:0;padding:0;box-sizing:border-box}:root{--bg:#f8fafc;--surface:#fff;--surface2:#f1f5f9;--ink:#0f172a;--ink2:#64748b;--line:#e2e8f0;--green:#059669;--green2:#047857;--green-soft:#ecfdf5;--gold:#d97706;--gold2:#b45309;--gold-soft:#fffbeb;--red:#dc2626;--red-soft:#fef2f2;--blue:#2563eb;--blue-soft:#eff6ff;--orange:#ea580c;--orange-soft:#fff7ed;--shadow:0 1px 3px rgba(0,0,0,.06),0 8px 24px rgba(0,0,0,.06);--shadow-sm:0 1px 2px rgba(0,0,0,.04);--fd:'Sora',sans-serif;--fb:'Manrope',sans-serif;--fm:'JetBrains Mono',monospace;--r:12px}[data-theme="dark"]{--bg:#0c1222;--surface:#1a2332;--surface2:#243044;--ink:#f1f5f9;--ink2:#94a3b8;--line:#2d3f56;--green:#34d399;--green2:#10b981;--green-soft:#064e3b;--gold:#fbbf24;--gold2:#f59e0b;--gold-soft:#451a03;--red:#f87171;--red-soft:#450a0a;--blue:#60a5fa;--blue-soft:#1e3a5f;--orange:#fb923c;--orange-soft:#431407;--shadow:0 1px 3px rgba(0,0,0,.3),0 8px 24px rgba(0,0,0,.3);--shadow-sm:0 1px 2px rgba(0,0,0,.2)}html{scroll-behavior:smooth}body{font-family:var(--fb);background:var(--bg);color:var(--ink);font-size:14px;line-height:1.5;transition:background .3s,color .3s;-webkit-font-smoothing:antialiased}body::before{content:'';position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(700px 420px at 88% -12%,color-mix(in srgb,var(--green) 10%,transparent),transparent 62%),radial-gradient(560px 380px at -12% 34%,color-mix(in srgb,var(--gold) 8%,transparent),transparent 60%)}.container{max-width:1400px;margin:0 auto;padding:0 20px}.mono{font-family:var(--fm)}svg{flex:none}button{font-family:inherit;cursor:pointer}input,select,textarea{font-family:inherit;font-size:13px;color:var(--ink)}::selection{background:color-mix(in srgb,var(--green) 25%,transparent)}.icon-svg{stroke:currentColor;fill:none;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.topbar{position:sticky;top:0;z-index:50;background:color-mix(in srgb,var(--surface) 88%,transparent);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.topbar .container{display:flex;align-items:center;gap:10px;padding-top:8px;padding-bottom:8px;flex-wrap:wrap}.brand{display:flex;align-items:center;gap:8px;margin-right:auto}.logo-chip{width:34px;height:34px;border-radius:8px;background:var(--surface);display:grid;place-items:center;box-shadow:var(--shadow-sm);overflow:hidden;border:1px solid var(--line)}.logo-chip img{width:28px;height:28px;object-fit:contain}.brand strong{font-family:var(--fd);font-size:12px;font-weight:800;display:block;line-height:1.2}.brand small{color:var(--ink2);font-size:9px;font-weight:600}.back-link{display:inline-flex;align-items:center;gap:4px;font-size:10px;font-weight:700;color:var(--ink2);padding:5px 10px;border-radius:7px;border:1px solid var(--line);background:var(--surface);transition:.2s}.back-link:hover{color:var(--green);border-color:var(--green)}.back-link svg{width:12px;height:12px}.badge{display:inline-flex;align-items:center;gap:3px;font-size:8px;font-weight:800;letter-spacing:.7px;padding:4px 8px;border-radius:99px}.badge.live{background:var(--green-soft);color:var(--green)}.badge.secure{background:var(--gold-soft);color:var(--gold2)}.theme-btn{width:30px;height:30px;border-radius:8px;border:1px solid var(--line);background:var(--surface);color:var(--ink2);display:grid;place-items:center;transition:.25s;cursor:pointer}.theme-btn:hover{color:var(--gold);border-color:var(--gold);transform:rotate(18deg)}.theme-btn svg{width:14px;height:14px}
.page-header{padding:20px 0 4px;display:flex;align-items:flex-end;justify-content:space-between;flex-wrap:wrap;gap:10px}.ph-left h1{font-family:var(--fd);font-weight:800;font-size:clamp(18px,2.5vw,24px);display:flex;align-items:center;gap:8px}.ph-left h1 em{font-style:normal;color:var(--green)}.ph-left h1 svg{width:20px;height:20px}.ph-left p{color:var(--ink2);font-weight:600;font-size:11px;margin-top:2px}
.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:12px 0}.stat{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:10px 12px;display:flex;gap:8px;align-items:center;box-shadow:var(--shadow-sm);transition:transform .25s,box-shadow .25s}.stat:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.stat .ic{width:32px;height:32px;border-radius:8px;display:grid;place-items:center;flex:none}.stat .ic svg{width:14px;height:14px}.stat .ic.g{background:var(--green-soft);color:var(--green)}.stat .ic.y{background:var(--gold-soft);color:var(--gold2)}.stat .ic.b{background:var(--blue-soft);color:var(--blue)}.stat .ic.r{background:var(--red-soft);color:var(--red)}.stat b{font-family:var(--fd);font-size:16px;font-weight:800;display:block;line-height:1.15}.stat span{font-size:9px;font-weight:700;color:var(--ink2);letter-spacing:.4px;text-transform:uppercase}
.filter-bar{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:10px 14px;display:flex;gap:8px;flex-wrap:wrap;align-items:end;margin-bottom:12px;box-shadow:var(--shadow-sm)}.ff{display:flex;flex-direction:column;gap:3px;flex:1;min-width:120px}.ff label{font-size:8px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:var(--ink2)}.ff input,.ff select{height:34px;border:1.5px solid var(--line);border-radius:8px;padding:0 10px;background:var(--surface2);font-size:12px;font-weight:600;outline:none;transition:.2s}.ff input:focus,.ff select:focus{border-color:var(--green);background:var(--surface)}.filter-actions{display:flex;gap:5px;align-items:end}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:5px;border:none;border-radius:8px;font-weight:800;font-size:11px;padding:0 12px;height:34px;transition:.2s;cursor:pointer;-webkit-tap-highlight-color:transparent}.btn:active{transform:scale(.97)}.btn svg{width:13px;height:13px}.btn-primary{background:linear-gradient(135deg,var(--green),var(--green2));color:#fff;box-shadow:0 2px 8px color-mix(in srgb,var(--green) 25%,transparent)}.btn-primary:hover{filter:brightness(1.07);transform:translateY(-1px)}.btn-ghost{background:var(--surface);border:1.5px solid var(--line);color:var(--ink)}.btn-ghost:hover{border-color:var(--green);color:var(--green)}.btn-danger{background:var(--red-soft);color:var(--red);border:1.5px solid transparent}.btn-danger:hover{background:var(--red);color:#fff}.btn-csv{background:linear-gradient(135deg,#059669,#047857);color:#fff}.btn-xls{background:linear-gradient(135deg,#1d4ed8,#1e40af);color:#fff}.btn-sm{height:28px;padding:0 9px;font-size:10px;border-radius:7px}
.bulk-bar{background:linear-gradient(135deg,var(--blue-soft),color-mix(in srgb,var(--blue-soft) 50%,var(--blue-soft)));border:1.5px solid color-mix(in srgb,var(--blue) 20%,transparent);border-radius:var(--r);padding:8px 14px;display:none;align-items:center;gap:8px;margin-bottom:10px;animation:bulkIn .3s ease}.bulk-bar.visible{display:flex}@keyframes bulkIn{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:none}}.bulk-count{font-family:var(--fm);font-weight:800;font-size:12px;color:var(--blue);background:var(--surface);padding:2px 9px;border-radius:99px;border:1px solid color-mix(in srgb,var(--blue) 20%,transparent)}.bulk-label{font-size:11px;font-weight:700;color:var(--ink);flex:1}.bulk-actions{display:flex;gap:5px;flex-wrap:wrap}
.table-card{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);box-shadow:var(--shadow-sm);overflow:hidden}.table-head{display:flex;justify-content:space-between;align-items:center;padding:10px 14px;border-bottom:1px solid var(--line)}.table-head h2{font-family:var(--fd);font-size:13px;font-weight:800;display:flex;align-items:center;gap:5px}.table-head h2 svg{width:14px;height:14px;stroke:var(--green)}.count-pill{font-family:var(--fm);font-size:9px;font-weight:700;background:var(--green-soft);color:var(--green);padding:2px 8px;border-radius:99px}.showing-note{text-align:center;padding:8px;font-size:10px;color:var(--ink2);font-weight:600;border-bottom:1px solid var(--line);background:var(--surface2)}.table-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}table{width:100%;border-collapse:collapse;min-width:1100px}thead th{font-size:8px;font-weight:800;letter-spacing:.7px;text-transform:uppercase;color:var(--ink2);text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);background:var(--surface2);white-space:nowrap}tbody td{padding:8px 10px;border-bottom:1px solid var(--line);font-size:11px;font-weight:600;vertical-align:middle}tbody tr{transition:background .15s}tbody tr:hover{background:var(--surface2)}tbody tr.selected{background:color-mix(in srgb,var(--blue) 6%,var(--surface))}tbody tr:last-child td{border-bottom:none}.row-chk{width:14px;height:14px;accent-color:var(--blue);cursor:pointer}.oid{font-size:10px;font-weight:700;color:var(--green);font-family:var(--fm)}.oc strong{display:block;font-weight:800;font-size:11px}.oc small{color:var(--ink2);font-weight:600;font-size:9px}.op{display:flex;align-items:center;gap:5px}.op img{width:22px;height:22px;border-radius:5px;object-fit:cover;border:1px solid var(--line)}.type-badge{font-size:7px;font-weight:800;padding:2px 6px;border-radius:99px;letter-spacing:.5px;text-transform:uppercase;display:inline-block}.type-badge.outbound{background:var(--orange-soft);color:var(--orange)}.type-badge.inbound{background:var(--blue-soft);color:var(--blue)}.route-cell{font-size:9px;color:var(--ink2);line-height:1.3}.route-cell b{color:var(--ink);font-weight:700;display:block;font-size:10px}.driver-cell{display:flex;align-items:center;gap:5px}.driver-cell .d-avatar{width:22px;height:22px;border-radius:50%;background:var(--blue-soft);color:var(--blue);display:grid;place-items:center;font-size:8px;font-weight:800;flex:none}.driver-cell .d-info{line-height:1.2}.driver-cell .d-name{font-size:10px;font-weight:700;display:block}.driver-cell .d-plate{font-size:8px;color:var(--ink2);font-weight:600;font-family:var(--fm)}.actions-cell{display:flex;gap:3px;white-space:nowrap}.empty{padding:36px 20px;text-align:center;color:var(--ink2)}.empty svg{width:32px;height:32px;stroke:var(--ink2);margin:0 auto 6px;opacity:.4;display:block}.empty p{font-weight:700;font-size:12px}.empty small{font-weight:600;font-size:10px}
.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,.5);backdrop-filter:blur(8px);display:none;align-items:center;justify-content:center;z-index:100;padding:20px}.modal-overlay.open{display:flex;animation:fadein .25s ease}@keyframes fadein{from{opacity:0}to{opacity:1}}.view-modal-wrap{background:var(--surface);border:1px solid var(--line);border-radius:16px;max-width:600px;width:100%;max-height:90vh;overflow-y:auto;position:relative;box-shadow:0 20px 60px rgba(0,0,0,.15);animation:modalSlide .35s cubic-bezier(.34,1.56,.64,1)}@keyframes modalSlide{from{opacity:0;transform:translateY(20px) scale(.97)}to{opacity:1;transform:translateY(0) scale(1)}}.vm-header{background:linear-gradient(135deg,var(--green),var(--green2));padding:16px 20px;border-radius:16px 16px 0 0;color:#fff;display:flex;align-items:center;justify-content:space-between}.vm-header h3{font-family:var(--fd);font-size:16px;font-weight:800;display:flex;align-items:center;gap:6px}.vm-header h3 svg{width:16px;height:16px}.vm-close{width:28px;height:28px;border-radius:7px;border:1px solid rgba(255,255,255,.3);background:rgba(255,255,255,.1);color:#fff;font-size:13px;cursor:pointer;display:grid;place-items:center}.vm-close:hover{background:rgba(255,255,255,.25)}.vm-body{padding:16px 20px 20px}
.vm-section{margin-bottom:14px}.vm-section-title{font-family:var(--fd);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.8px;color:var(--green);margin-bottom:8px;padding-bottom:5px;border-bottom:2px solid var(--green-soft);display:flex;align-items:center;gap:5px}.vm-section-title svg{width:13px;height:13px;stroke:var(--green)}.vm-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.vm-field{background:var(--surface2);border:1px solid var(--line);border-radius:8px;padding:8px 10px}.vm-field.full{grid-column:1/-1}.vm-field .vf-label{font-size:7px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:var(--ink2);margin-bottom:2px;display:block}.vm-field .vf-value{font-size:12px;font-weight:700;color:var(--ink);word-break:break-word}.vm-field .vf-value.mono{font-family:var(--fm);color:var(--green)}.vm-field .vf-value.empty{color:var(--ink2);font-style:italic;font-weight:500;font-size:10px}
.ef-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px}.ef-field{display:flex;flex-direction:column;gap:3px}.ef-field.full{grid-column:1/-1}.ef-label{font-size:8px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:var(--ink2)}.ef-label b{color:var(--red)}.ef-ctrl{display:flex;align-items:center;gap:6px;background:var(--surface2);border:1.5px solid var(--line);border-radius:8px;padding:0 10px;height:36px;transition:.2s}.ef-ctrl:focus-within{border-color:var(--green);box-shadow:0 0 0 3px color-mix(in srgb,var(--green) 10%,transparent);background:var(--surface)}.ef-ctrl input,.ef-ctrl select,.ef-ctrl textarea{flex:1;border:none;outline:none;background:transparent;height:100%;font-weight:600;width:100%;font-size:12px}.ef-ctrl textarea{padding:8px 0;height:auto;min-height:40px;resize:vertical}.ef-ctrl.ta{height:auto;align-items:flex-start;padding-top:2px}
footer{margin-top:20px;border-top:1px solid var(--line);padding:14px 20px 20px;text-align:center;color:var(--ink2);font-size:10px;font-weight:700}footer div+div{margin-top:2px;font-weight:600;opacity:.7}
.toasts{position:fixed;top:60px;right:14px;z-index:120;display:flex;flex-direction:column;gap:6px}.toast{display:flex;align-items:center;gap:6px;background:var(--surface);border:1px solid var(--line);border-left:3px solid var(--green);border-radius:8px;padding:8px 12px;font-size:11px;font-weight:700;box-shadow:var(--shadow);animation:slidein .3s;max-width:320px}.toast.error{border-left-color:var(--red)}.toast.info{border-left-color:var(--blue)}.toast.out{opacity:0;transform:translateX(20px);transition:.4s}@keyframes slidein{from{transform:translateX(30px);opacity:0}to{transform:none;opacity:1}}
#printSheet{display:none}
@media print{
  @page{size:A4;margin:10mm}
  *{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}
  body{background:#fff!important;margin:0!important;padding:0!important;min-height:auto!important}
  body::before,body>*:not(#printSheet){display:none!important;visibility:hidden!important;height:0!important;max-height:0!important;overflow:hidden!important;position:absolute!important;left:-9999px!important;margin:0!important;padding:0!important;border:none!important}
  #printSheet{display:block!important;visibility:visible!important;position:static!important;height:auto!important;max-height:none!important;overflow:visible!important;left:auto!important;width:100%!important;margin:0!important;padding:0!important}
}
@media(max-width:1020px){.stats{grid-template-columns:repeat(2,1fr)}}
@media(max-width:768px){.stats{grid-template-columns:1fr 1fr;gap:6px}.page-header{flex-direction:column;align-items:flex-start}.filter-bar{flex-direction:column}.ff{min-width:100%}.filter-actions{width:100%}.filter-actions .btn{flex:1}.topbar .badge{display:none}.actions-cell{flex-direction:column;gap:3px}.actions-cell .btn-sm{width:100%;justify-content:center}.ef-grid{grid-template-columns:1fr}.vm-grid{grid-template-columns:1fr}}
@media(max-width:480px){.stats{grid-template-columns:1fr}}
</style>
</head>
<body>
<header class="topbar"><div class="container"><div class="brand"><div class="logo-chip"><img src="logo.ico" alt="Logo"></div><div><strong><?php echo e($company['company_name']); ?></strong><small><?php echo e($company['company_dept']); ?></small></div></div><a href="admin_general_dashboard.php" class="back-link"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M19 12H5"/><path d="m12 19-7-7 7-7"/></svg>Dashboard</a><span class="badge live">ONLINE</span><span class="badge secure">SECURE</span><button class="theme-btn" id="themeBtn" title="Toggle theme"><svg class="icon-svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="4.5"/><path d="M12 2v2.5M12 19.5V22M2 12h2.5M19.5 12H22M4.6 4.6l1.8 1.8M17.6 17.6l1.8 1.8M4.6 19.4l1.8-1.8M17.6 6.4l1.8-1.8"/></svg></button></div></header>
<div class="container">
  <div class="page-header"><div class="ph-left"><h1><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg> Order <em>Register</em></h1><p>Track orders, drivers, routes &amp; export for disbursement</p></div></div>
  <section class="stats">
    <div class="stat"><div class="ic g"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg></div><div><b><?php echo number_format($totalOrders); ?></b><span>Total Orders</span></div></div>
    <div class="stat"><div class="ic y"><svg class="icon-svg" viewBox="0 0 24 24"><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/></svg></div><div><b><?php echo fmtN($totalRevenue); ?></b><span>Revenue</span></div></div>
    <div class="stat"><div class="ic b"><svg class="icon-svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><div><b><?php echo number_format($pendingCount); ?></b><span>Pending</span></div></div>
    <div class="stat"><div class="ic r"><svg class="icon-svg" viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"/></svg></div><div><b><?php echo number_format($deliveredCnt); ?></b><span>Delivered</span></div></div>
  </section>
  <form method="get" class="filter-bar">
    <div class="ff"><label>Search</label><input type="text" name="search" placeholder="Order, client, route..." value="<?php echo e($search); ?>"></div>
    <div class="ff" style="max-width:130px"><label>Status</label><select name="status"><option value="">All</option><option value="Pending" <?php echo $filterStatus==='Pending'?'selected':''; ?>>Pending</option><option value="Approved" <?php echo $filterStatus==='Approved'?'selected':''; ?>>Approved</option><option value="Delivered" <?php echo $filterStatus==='Delivered'?'selected':''; ?>>Delivered</option></select></div>
    <div class="ff" style="max-width:130px"><label>Date</label><input type="date" name="date" value="<?php echo e($filterDate); ?>"></div>
    <div class="filter-actions"><button type="submit" class="btn btn-primary"><svg class="icon-svg" viewBox="0 0 24 24"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg> Filter</button><a href="order_register.php" class="btn btn-ghost">Clear</a></div>
  </form>
  <div class="bulk-bar" id="bulkBar"><span class="bulk-count" id="bulkCount">0</span><span class="bulk-label">orders selected</span><div class="bulk-actions"><button type="button" class="btn btn-csv btn-sm" id="btnExportCsv"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg> CSV</button><button type="button" class="btn btn-xls btn-sm" id="btnExportXls"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg> Excel</button><button type="button" class="btn btn-ghost btn-sm" id="btnClearSel">Clear</button></div></div>
  <div class="table-card">
    <div class="table-head"><h2><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg> All Orders</h2><span class="count-pill"><?php echo count($orders); ?> records</span></div>
    <?php if(!$hasFilter && count($orders)>0): ?><div class="showing-note">Showing latest 10 orders — use filters to view all</div><?php endif; ?>
    <div class="table-wrap"><table id="ordersTable"><thead><tr><th style="width:32px"><input type="checkbox" class="row-chk" id="selectAll"></th><th>Order #</th><th>Type</th><th>Client</th><th>Product</th><th>Qty</th><th>Total</th><th>Truck</th><th>Route</th><th>Driver</th><th>Status</th><th>Paid</th><th>Date</th><th>Actions</th></tr></thead><tbody>
      <?php if(empty($orders)): ?><tr><td colspan="14"><div class="empty"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg><p>No orders found</p><small>Adjust filters or create a new order.</small></div></td></tr>
      <?php else: foreach($orders as $o):
        $oType=(string)($o['order_type']??'outbound');$depart=(string)($o['departure_location']??'');$dest=(string)($o['destination_location']??'');$truckP=(float)($o['truck_price']??0);$drvName=(string)($o['driver_name']??'');$drvPlate=(string)($o['driver_plate']??'');$drvInitial=$drvName?strtoupper(substr(trim($drvName),0,1)):'?';$clientName=(string)($o['client_name']??'');$clientPhone=(string)($o['client_phone']??'');$clientEmail=(string)($o['client_email']??'');$prodName=(string)($o['product_name']??'');$bankName=(string)($o['bank_name']??'');$accNo=(string)($o['account_no']??'');$accName=(string)($o['account_name']??'');$kgVal=(float)($o['kilograms']??0);$upVal=(float)($o['unit_price']??0);$totVal=(float)($o['total_amount']??0);$ordDate=(string)($o['order_date']??'');$createdAt=(string)($o['created_at']??'');$ordStatus=(string)($o['status']??'');$ordPaid=(int)($o['is_paid']??0);
      ?>
        <tr data-id="<?php echo (int)$o['id']; ?>" data-bank='<?php echo json_encode(["order_no"=>(string)$o["order_no"],"order_type"=>$oType,"client"=>$clientName,"phone"=>$clientPhone,"email"=>$clientEmail,"bank"=>$bankName,"acc_no"=>$accNo,"acc_name"=>$accName,"amount"=>$totVal,"truck_price"=>$truckP,"departure"=>$depart,"destination"=>$dest,"driver"=>$drvName,"driver_plate"=>$drvPlate,"product"=>$prodName,"kg"=>$kgVal,"unit_price"=>$upVal,"status"=>$ordStatus,"is_paid"=>$ordPaid,"date"=>$ordDate,"created_at"=>$createdAt,"description"=>$o['description']??''],JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT); ?>'>
          <td><input type="checkbox" class="row-chk order-chk" value="<?php echo (int)$o['id']; ?>"></td>
          <td class="mono oid"><?php echo e($o['order_no']); ?></td>
          <td><span class="type-badge <?php echo $oType; ?>"><?php echo ucfirst($oType); ?></span></td>
          <td><div class="oc"><strong><?php echo e($clientName); ?></strong><small><?php echo e($clientPhone); ?></small></div></td>
          <td><div class="op"><?php if(!empty($o['product_img'])): ?><img src="<?php echo e($o['product_img']); ?>" alt=""><?php endif; ?><span><?php echo e($prodName); ?></span></div></td>
          <td class="mono"><?php echo number_format($kgVal); ?> kg</td>
          <td class="mono"><?php echo fmtN($totVal); ?></td>
          <td class="mono"><?php echo $truckP>0?fmtN($truckP):'—'; ?></td>
          <td><div class="route-cell"><?php if($depart||$dest): ?><b><?php echo e($depart?:'—'); ?></b><span style="font-size:8px">&#8594; <?php echo e($dest?:'—'); ?></span><?php else: ?>—<?php endif; ?></div></td>
          <td><?php if($drvName): ?><div class="driver-cell"><div class="d-avatar"><?php echo $drvInitial; ?></div><div class="d-info"><span class="d-name"><?php echo e($drvName); ?></span><?php if($drvPlate): ?><span class="d-plate"><?php echo e($drvPlate); ?></span><?php endif; ?></div></div><?php else: ?><span style="color:var(--ink2);font-size:9px">—</span><?php endif; ?></td>
          <td><span class="type-badge" style="background:<?php echo $ordStatus==='Delivered'?'var(--green-soft)':($ordStatus==='Approved'?'var(--blue-soft)':'var(--gold-soft)'); ?>;color:<?php echo $ordStatus==='Delivered'?'var(--green)':($ordStatus==='Approved'?'var(--blue)':'var(--gold2)'); ?>"><?php echo e($ordStatus); ?></span></td>
          <td><span style="font-size:9px;font-weight:700;color:<?php echo $ordPaid?'var(--green)':'var(--ink2)'; ?>"><?php echo $ordPaid?'Yes':'No'; ?></span></td>
          <td style="font-size:10px;color:var(--ink2)"><?php echo $ordDate?date('d M Y',strtotime($ordDate)):'—'; ?></td>
          <td><div class="actions-cell">
            <button type="button" class="btn btn-ghost btn-sm btn-view" data-order='<?php echo json_encode($o,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT); ?>'><svg class="icon-svg" viewBox="0 0 24 24"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg></button>
            <button type="button" class="btn btn-ghost btn-sm btn-edit-full" data-order='<?php echo json_encode($o,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT); ?>'><svg class="icon-svg" viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button>
            <button type="button" class="btn btn-ghost btn-sm btn-print-ticket" data-order='<?php echo json_encode($o,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT); ?>'><svg class="icon-svg" viewBox="0 0 24 24"><polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg></button>
            <button type="button" class="btn btn-danger btn-sm btn-delete" data-id="<?php echo (int)$o['id']; ?>" data-no="<?php echo e($o['order_no']); ?>"><svg class="icon-svg" viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button>
          </div></td>
        </tr>
      <?php endforeach; endif; ?>
    </tbody></table></div>
  </div>
</div>
<footer><div>&copy; 2026 <?php echo e($company['company_name']); ?></div><div>Enterprise HR &amp; Operations System</div><div>Developed by Lawani Djamiou Alade</div></footer>

<!-- DELETE MODAL -->
<div class="modal-overlay" id="deleteModal"><div class="view-modal-wrap" style="max-width:380px"><div class="vm-header" style="background:linear-gradient(135deg,var(--red),#b91c1c)"><h3><svg class="icon-svg" viewBox="0 0 24 24" style="stroke:#fff"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg> Delete Order?</h3><button class="vm-close" onclick="closeModal('deleteModal')">&times;</button></div><div class="vm-body" style="text-align:center"><p style="color:var(--ink2);font-size:11px;margin-bottom:12px">This cannot be undone.</p><div style="font-family:var(--fm);font-weight:700;font-size:11px;background:var(--red-soft);color:var(--red);padding:5px 10px;border-radius:7px;display:inline-block;margin-bottom:12px" id="deleteOrderNo">—</div><form method="post"><input type="hidden" name="action" value="delete_order"><input type="hidden" name="order_id" id="deleteOrderId"><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button type="button" class="btn btn-ghost" onclick="closeModal('deleteModal')">Cancel</button><button type="submit" class="btn btn-danger">Delete</button></div></form></div></div></div>

<!-- VIEW MODAL -->
<div class="modal-overlay" id="viewModal"><div class="view-modal-wrap"><div class="vm-header"><div><h3 id="vmTitle">Order Details</h3></div><button class="vm-close" onclick="closeModal('viewModal')">&times;</button></div><div class="vm-body" id="vmBody"></div><div style="padding:12px 20px;border-top:1px solid var(--line);display:flex;justify-content:flex-end"><button class="btn btn-ghost" onclick="closeModal('viewModal')">Close</button></div></div></div>

<!-- EDIT MODAL -->
<div class="modal-overlay" id="editModal"><div class="view-modal-wrap"><div class="vm-header"><div><h3><svg class="icon-svg" viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg> Edit Order</h3></div><button class="vm-close" onclick="closeModal('editModal')">&times;</button></div><div class="vm-body"><form method="post" id="editForm">
<input type="hidden" name="action" value="update_order_full"><input type="hidden" name="order_id" id="ef_id">
<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg> Order Info</div><div class="ef-grid"><div class="ef-field"><label class="ef-label">Order Date <b>*</b></label><div class="ef-ctrl"><input type="date" name="order_date" id="ef_date"></div></div><div class="ef-field"><label class="ef-label">Type</label><div class="ef-ctrl"><select name="order_type" id="ef_type"><option value="outbound">Outbound</option><option value="inbound">Inbound</option></select></div></div><div class="ef-field full"><label class="ef-label">Description</label><div class="ef-ctrl ta"><textarea name="description" id="ef_desc" rows="2"></textarea></div></div></div></div>
<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg> Product &amp; Pricing</div><div class="ef-grid"><div class="ef-field"><label class="ef-label">Kilograms <b>*</b></label><div class="ef-ctrl"><input type="number" name="kilograms" id="ef_kg" step="0.01" min="0"></div></div><div class="ef-field"><label class="ef-label">Unit Price <b>*</b></label><div class="ef-ctrl"><input type="number" name="unit_price" id="ef_price" step="0.01" min="0"></div></div></div></div>
<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg> Logistics</div><div class="ef-grid"><div class="ef-field"><label class="ef-label">Departure</label><div class="ef-ctrl"><input name="departure_location" id="ef_depart"></div></div><div class="ef-field"><label class="ef-label">Destination</label><div class="ef-ctrl"><input name="destination_location" id="ef_dest"></div></div><div class="ef-field"><label class="ef-label">Truck Price</label><div class="ef-ctrl"><input type="number" name="truck_price" id="ef_truck" step="0.01" min="0"></div></div></div></div>
<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M3 21h18M3 10h18M5 6l7-3 7 3M4 10v11M20 10v11M8 14v3M12 14v3M16 14v3"/></svg> Bank Details</div><div class="ef-grid"><div class="ef-field"><label class="ef-label">Bank Name</label><div class="ef-ctrl"><input name="bank" id="ef_bank"></div></div><div class="ef-field"><label class="ef-label">Account No</label><div class="ef-ctrl"><input name="account_no" id="ef_accno"></div></div><div class="ef-field full"><label class="ef-label">Account Name</label><div class="ef-ctrl"><input name="account_name" id="ef_accname"></div></div></div></div>
<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Status</div><div class="ef-grid"><div class="ef-field"><label class="ef-label">Status</label><div class="ef-ctrl"><select name="status" id="ef_status"><option value="Pending">Pending</option><option value="Approved">Approved</option><option value="Delivered">Delivered</option></select></div></div><div class="ef-field"><label class="ef-label">Paid</label><div class="ef-ctrl"><select name="is_paid" id="ef_paid"><option value="0">No</option><option value="1">Yes</option></select></div></div></div></div>
<button type="submit" class="btn btn-primary" style="width:100%;height:44px;font-size:14px;margin-top:8px"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg> Save Changes</button>
</form></div></div></div>

<div class="toasts" id="toastWrap"></div>
<div id="printSheet" aria-hidden="true"></div>

<script>
var $=function(id){return document.getElementById(id)};
var esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c})};
var fmt=function(n){return '\u20A6'+Number(n||0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})};
var CO={name:<?php echo json_encode($company['company_name']); ?>,addr:<?php echo json_encode($company['company_address']); ?>,dept:<?php echo json_encode($company['company_dept']); ?>,tag:<?php echo json_encode($company['company_tagline']); ?>};

function toast(msg,type){var t=document.createElement('div');t.className='toast '+(type==='error'?'error':(type==='info'?'info':''));t.innerHTML='<span>'+(type==='error'?'\u26A0\uFE0F':'\u2705')+'</span>'+esc(msg);$('toastWrap').appendChild(t);setTimeout(function(){t.classList.add('out')},3000);setTimeout(function(){t.remove()},3500);}
var store={get:function(k,d){try{var v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}},set:function(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
var sunSVG='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><circle cx="12" cy="12" r="4.5"/><path d="M12 2v2.5M12 19.5V22M2 12h2.5M19.5 12H22M4.6 4.6l1.8 1.8M17.6 17.6l1.8 1.8M4.6 19.4l1.8-1.8M17.6 6.4l1.8-1.8"/></svg>';
var moonSVG='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/></svg>';
function setTheme(t){document.documentElement.dataset.theme=t;store.set('okoya_theme',t);$('themeBtn').innerHTML=t==='dark'?sunSVG:moonSVG;}
$('themeBtn').addEventListener('click',function(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')});
setTheme(store.get('okoya_theme','light'));

function closeModal(id){$(id).classList.remove('open')}
document.querySelectorAll('.modal-overlay').forEach(function(m){m.addEventListener('click',function(e){if(e.target===m)m.classList.remove('open')})});
document.addEventListener('keydown',function(e){if(e.key==='Escape')document.querySelectorAll('.modal-overlay.open').forEach(function(m){m.classList.remove('open')})});

function updateBulkBar(){var checked=document.querySelectorAll('.order-chk:checked');$('bulkCount').textContent=checked.length;$('bulkBar').classList.toggle('visible',checked.length>0);document.querySelectorAll('tr[data-id]').forEach(function(tr){var chk=tr.querySelector('.order-chk');tr.classList.toggle('selected',chk&&chk.checked)});}
$('selectAll').addEventListener('change',function(){document.querySelectorAll('.order-chk').forEach(function(c){c.checked=this.checked});updateBulkBar()});
document.querySelectorAll('.order-chk').forEach(function(c){c.addEventListener('change',updateBulkBar)});
$('btnClearSel').addEventListener('click',function(){document.querySelectorAll('.order-chk').forEach(function(c){c.checked=false});$('selectAll').checked=false;updateBulkBar()});

function getSelectedData(){var selected=[];document.querySelectorAll('tr[data-id]').forEach(function(tr){var chk=tr.querySelector('.order-chk');if(chk&&chk.checked){try{selected.push(JSON.parse(tr.dataset.bank))}catch(e){}}});return selected;}

$('btnExportCsv').addEventListener('click',function(){
  var selected=getSelectedData();if(!selected.length){toast('No orders selected','error');return;}
  var csv='\ufeffReciever Name,Reciever Account No,Amount,Sender Narration,Receiever\'s Narration,BankCode\n';
  selected.forEach(function(s){var n='Salary Payment - '+new Date().toLocaleDateString('en-NG',{month:'long',year:'numeric'});csv+=['"'+String(s.client||'').replace(/"/g,'""')+'"','"'+String(s.acc_no||'').replace(/"/g,'""')+'"','"'+Number(s.amount||0).toFixed(2)+'"','"'+n.replace(/"/g,'""')+'"','"'+String(s.client||'').replace(/"/g,'""')+'"','""'].join(',')+'\n';});
  var blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='Bulk-Payment-Upload-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);toast('CSV exported ('+selected.length+')','success');
});

$('btnExportXls').addEventListener('click',function(){
  var selected=getSelectedData();if(!selected.length){toast('No orders selected','error');return;}
  var h='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><style>body{font-family:Calibri,sans-serif;font-size:11pt}table{border-collapse:collapse;width:100%}th{background:#059669;color:#fff;font-size:9pt;font-weight:bold;padding:6pt 8pt;text-align:left;border:1pt solid #047857}td{padding:5pt 8pt;border:1pt solid #ddd;font-size:10pt}.money{mso-number-format:"\\#\\,\\#\\#0\\.00";text-align:right}</style></head><body><table><tr><th>Receiver Full Name</th><th>Account no/Mobile no/Card no</th><th>Card Client Id</th><th>Wallet Provider</th><th>Amount in NGN</th><th>Bank Name/Institution Name</th></tr>';
  selected.forEach(function(s){h+='<tr><td>'+esc(s.client||'')+'</td><td style="mso-number-format:\\@">'+esc(s.acc_no||'')+'</td><td></td><td></td><td class="money">'+Number(s.amount||0).toFixed(2)+'</td><td>'+esc(s.bank||'')+'</td></tr>';});
  h+='</table></body></html>';
  var blob=new Blob(['\ufeff'+h],{type:'application/vnd.ms-excel'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download='Salary-Disbursement-'+new Date().toISOString().slice(0,10)+'.xls';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);toast('Excel exported ('+selected.length+')','success');
});

$('deleteModal').addEventListener('click',function(e){if(e.target===$('deleteModal'))closeModal('deleteModal')});
document.querySelectorAll('.btn-delete').forEach(function(b){b.addEventListener('click',function(){$('deleteOrderId').value=b.dataset.id;$('deleteOrderNo').textContent=b.dataset.no;$('deleteModal').classList.add('open')})});

$('viewModal').addEventListener('click',function(e){if(e.target===$('viewModal'))closeModal('viewModal')});
document.querySelectorAll('.btn-view').forEach(function(b){b.addEventListener('click',function(){
  var tr=b.closest('tr');try{var d=JSON.parse(tr.dataset.bank)}catch(e){toast('Error loading data','error');return;}
  function field(label,value,isMono,isFull){var hasVal=value&&String(value).trim()!==''&&String(value)!=='0';var cls='vm-field'+(isFull?' full':'');var valCls='vf-value'+(isMono?' mono':'')+(hasVal?'':' empty');return '<div class="'+cls+'"><span class="vf-label">'+label+'</span><span class="'+valCls+'">'+(hasVal?esc(String(value)):'Not provided')+'</span></div>';}
  var h='<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg> Order Information</div><div class="vm-grid">'+field('Order Number',d.order_no,true,false)+field('Order Type',(d.order_type||'outbound').toUpperCase(),false,false)+field('Order Date',d.date,false,false)+field('Status',d.status,false,false)+field('Payment',d.is_paid==1?'Paid':'Unpaid',false,false)+field('Created',d.created_at||d.date,false,false)+field('Description',d.description,false,true)+'</div></div>';
  h+='<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg> Client</div><div class="vm-grid">'+field('Client Name',d.client,false,true)+field('Phone',d.phone,false,false)+field('Email',d.email,false,false)+'</div></div>';
  h+='<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/></svg> Product</div><div class="vm-grid">'+field('Product',d.product,false,true)+field('Quantity',d.kg>0?Number(d.kg).toLocaleString()+' kg':null,false,false)+field('Unit Price',d.unit_price>0?fmt(d.unit_price):null,true,false)+'</div></div>';
  h+='<div style="background:linear-gradient(135deg,var(--green),var(--green2));border-radius:10px;padding:12px 16px;color:#fff;display:flex;justify-content:space-between;align-items:center;margin:14px 0"><span style="font-size:8px;font-weight:800;letter-spacing:1px;text-transform:uppercase;opacity:.85">Total Amount</span><span style="font-family:var(--fm);font-size:18px;font-weight:700">'+fmt(d.amount)+'</span></div>';
  h+='<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg> Logistics</div><div class="vm-grid">'+field('Driver',d.driver,false,false)+field('Vehicle Plate',d.driver_plate,false,false)+field('Truck Price',d.truck_price>0?fmt(d.truck_price):null,true,false)+field('Departure',d.departure,false,false)+field('Destination',d.destination,false,false)+'</div></div>';
  h+='<div class="vm-section"><div class="vm-section-title"><svg class="icon-svg" viewBox="0 0 24 24"><path d="M3 21h18M3 10h18M5 6l7-3 7 3M4 10v11M20 10v11M8 14v3M12 14v3M16 14v3"/></svg> Bank Details</div><div class="vm-grid">'+field('Bank Name',d.bank,false,true)+field('Account Number',d.acc_no,true,false)+field('Account Name',d.acc_name,false,true)+'</div></div>';
  $('vmTitle').textContent=d.order_no||'Order Details';$('vmBody').innerHTML=h;$('viewModal').classList.add('open');
})});

$('editModal').addEventListener('click',function(e){if(e.target===$('editModal'))closeModal('editModal')});
document.querySelectorAll('.btn-edit-full').forEach(function(b){b.addEventListener('click',function(){
  var tr=b.closest('tr');try{var d=JSON.parse(tr.dataset.bank)}catch(e){toast('Error loading data','error');return;}
  $('ef_id').value=tr.dataset.id;$('ef_date').value=d.date||'';$('ef_type').value=d.order_type||'outbound';$('ef_desc').value=d.description||'';$('ef_kg').value=d.kg||'';$('ef_price').value=d.unit_price||'';$('ef_depart').value=d.departure||'';$('ef_dest').value=d.destination||'';$('ef_truck').value=d.truck_price||'';$('ef_bank').value=d.bank||'';$('ef_accno').value=d.acc_no||'';$('ef_accname').value=d.acc_name||'';$('ef_status').value=d.status||'Pending';$('ef_paid').value=d.is_paid==1?'1':'0';
  $('editModal').classList.add('open');
})});

/* PRINT TICKET - Only prints dedicated document */
function printTicket(d){
  var now=new Date().toLocaleString('en-NG',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
  var netKg=Number(d.kg||0);
  var h='<div style="font-family:Arial,Helvetica,sans-serif;color:#1a231d;font-size:9pt">'+
  '<div style="display:flex;align-items:center;gap:12pt;border-bottom:3pt double #059669;padding-bottom:10pt;margin-bottom:12pt">'+
    '<img class="pt-logo" src="logo.ico" alt="Logo">'+
    '<div style="flex:1"><div style="font-size:14pt;font-weight:800;color:#059669;line-height:1.15">'+esc(CO.name)+'</div><div style="font-size:6.5pt;color:#5a655c;margin-top:2pt">'+esc(CO.addr)+'</div><div style="font-size:6pt;color:#5a655c;margin-top:1pt">'+esc(CO.dept)+'</div><div style="font-size:4.5pt;font-weight:800;letter-spacing:1.2pt;color:#b57e17;margin-top:2pt;text-transform:uppercase">'+esc(CO.tag)+'</div></div>'+
    '<div style="text-align:right;flex:none"><div style="background:#059669;color:#fff;font-size:8pt;font-weight:800;letter-spacing:1pt;padding:4pt 10pt;border-radius:3pt;display:inline-block;margin-bottom:3pt">ORDER TICKET</div><div style="font-family:monospace;font-size:11pt;font-weight:700;color:#059669;margin-top:2pt">'+esc(d.order_no)+'</div><div style="font-size:5.5pt;color:#667268;margin-top:2pt">Date: '+esc(d.date)+'</div><div style="font-size:5.5pt;color:#667268;margin-top:1pt">Printed: '+now+'</div></div>'+
  '</div>'+
  '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8pt;margin-bottom:8pt">'+
    '<div style="border:1pt solid #dfe5dd;border-radius:4pt;overflow:hidden"><div style="background:#f1f5f9;font-size:5.5pt;font-weight:800;letter-spacing:.8pt;text-transform:uppercase;padding:3pt 7pt;border-bottom:1pt solid #dfe5dd;color:#64748b">Client Information</div><div style="padding:6pt 7pt"><div style="font-weight:700;font-size:9.5pt">'+esc(d.client||'Walk-in Client')+'</div><div style="font-size:6.5pt;color:#64748b;margin-top:2pt">'+esc(d.phone||'—')+'</div><div style="font-size:6.5pt;color:#64748b;margin-top:1pt">'+esc(d.email||'—')+'</div></div></div>'+
    '<div style="border:1pt solid #dfe5dd;border-radius:4pt;overflow:hidden"><div style="background:#f1f5f9;font-size:5.5pt;font-weight:800;letter-spacing:.8pt;text-transform:uppercase;padding:3pt 7pt;border-bottom:1pt solid #dfe5dd;color:#64748b">Product Details</div><div style="padding:6pt 7pt"><div style="font-weight:700;font-size:9.5pt">'+esc(d.product||'—')+'</div><div style="font-size:6.5pt;color:#64748b;margin-top:2pt">'+netKg.toLocaleString()+' kg @ '+fmt(d.unit_price||0)+'/kg</div>'+(d.description?'<div style="font-size:6pt;color:#64748b;margin-top:2pt;font-style:italic">'+esc(d.description)+'</div>':'')+'</div></div>'+
  '</div>'+
  '<div style="background:#059669;color:#fff;border-radius:6pt;padding:10pt 14pt;display:flex;justify-content:space-between;align-items:center;margin-bottom:8pt"><span style="font-size:6pt;font-weight:800;letter-spacing:1pt;text-transform:uppercase;opacity:.85">Total Amount</span><span style="font-family:monospace;font-size:18pt;font-weight:700">'+fmt(d.amount||0)+'</span></div>'+
  '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8pt;margin-bottom:8pt">'+
    '<div style="border:1pt solid #dfe5dd;border-radius:4pt;overflow:hidden"><div style="background:#f1f5f9;font-size:5.5pt;font-weight:800;letter-spacing:.8pt;text-transform:uppercase;padding:3pt 7pt;border-bottom:1pt solid #dfe5dd;color:#64748b">Logistics &amp; Route</div><div style="padding:6pt 7pt"><div style="font-size:6.5pt;margin-bottom:2pt"><b>Driver:</b> '+esc(d.driver||'Not assigned')+(d.driver_plate?' ('+esc(d.driver_plate)+')':'')+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>Truck Cost:</b> '+(d.truck_price>0?fmt(d.truck_price):'—')+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>Type:</b> '+esc((d.order_type||'outbound').toUpperCase())+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>From:</b> '+esc(d.departure||'—')+'</div><div style="font-size:6.5pt"><b>To:</b> '+esc(d.destination||'—')+'</div></div></div>'+
    '<div style="border:1pt solid #dfe5dd;border-radius:4pt;overflow:hidden"><div style="background:#f1f5f9;font-size:5.5pt;font-weight:800;letter-spacing:.8pt;text-transform:uppercase;padding:3pt 7pt;border-bottom:1pt solid #dfe5dd;color:#64748b">Payment &amp; Bank</div><div style="padding:6pt 7pt"><div style="font-size:6.5pt;margin-bottom:2pt"><b>Bank:</b> '+esc(d.bank||'—')+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>Acc No:</b> '+esc(d.acc_no||'—')+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>Acc Name:</b> '+esc(d.acc_name||'—')+'</div><div style="font-size:6.5pt;margin-bottom:2pt"><b>Status:</b> '+esc(d.status||'Pending')+'</div><div style="font-size:6.5pt"><b>Paid:</b> '+(d.is_paid==1?'Yes':'No')+'</div></div></div>'+
  '</div>'+
  '<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12pt;margin-top:14pt"><div style="text-align:center"><div style="height:30pt;border-bottom:1.5pt solid #4a554c;margin-bottom:3pt"></div><span style="font-size:5pt;font-weight:800;letter-spacing:.6pt;text-transform:uppercase;color:#5a554c">Client Signature</span><small style="font-size:4.5pt;color:#9aa79c;display:block;margin-top:1pt">Name &amp; Date</small></div><div style="text-align:center"><div style="height:30pt;border-bottom:1.5pt solid #4a554c;margin-bottom:3pt"></div><span style="font-size:5pt;font-weight:800;letter-spacing:.6pt;text-transform:uppercase;color:#5a554c">Dispatch Officer</span><small style="font-size:4.5pt;color:#9aa79c;display:block;margin-top:1pt">Name &amp; Date</small></div><div style="text-align:center"><div style="height:30pt;border-bottom:1.5pt solid #4a554c;margin-bottom:3pt"></div><span style="font-size:5pt;font-weight:800;letter-spacing:.6pt;text-transform:uppercase;color:#5a554c">Authorised By</span><small style="font-size:4.5pt;color:#9aa79c;display:block;margin-top:1pt">Name &amp; Date</small></div></div>'+
  '<div style="margin-top:10pt;padding-top:5pt;border-top:1pt solid #dfe5dd;display:flex;justify-content:space-between;font-size:5pt;color:#9aa79c"><span style="color:#c0392b;font-weight:800;letter-spacing:.5pt">CONFIDENTIAL — INTERNAL USE ONLY</span><span>'+esc(CO.name)+' &mdash; '+esc(d.order_no)+'</span><span>'+now+'</span></div>'+
  '</div>';
  var ps=$('printSheet');ps.innerHTML=h;
  toast('Preparing print...','success');
  setTimeout(function(){window.print();setTimeout(function(){ps.innerHTML='';},1000)},300);
}

document.querySelectorAll('.btn-print-ticket').forEach(function(b){b.addEventListener('click',function(){var tr=b.closest('tr');try{var d=JSON.parse(tr.dataset.bank);printTicket(d)}catch(e){toast('Error loading order','error')}})});

<?php if($flashData): ?>
window.addEventListener('DOMContentLoaded',function(){toast(<?php echo json_encode($flashData['msg'],JSON_HEX_TAG|JSON_HEX_QUOT); ?>,'<?php echo $flashData['type']; ?>')});
<?php endif; ?>
</script>
</body>
</html>